# Generated by Django 6.1.1 on 2026-09-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_color',
        ),
        migrations.AddField(
            model_name='game',
            name='demo_gif',
            field=models.CharField(blank=True, help_text='Demo GIF filename e.g. demo1.gif (in media/images/)', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.CharField(help_text='Image filename e.g. 1.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_file',
            field=models.CharField(help_text='Python filename e.g. neon_racer.py', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='plays',
            field=models.IntegerField(default=0),
        ),
    ]
